<<<<<<< HEAD
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = ''
theme = 'ananke'

[params]
  custom_css = ["css/custom.css"]
  body_classes = "bg-black white"
  site_logo = ""
  description = ""
  background_color_class = "bg-black"
  recent_posts_number = 0
  footer = ""
=======
baseURL = "https://arranwalshe.com"
languageCode = "en-us"
title = "Arran Walshe"
theme = "ananke"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
  description = "Academic & Researcher"
  custom_css = ["/custom.css"]
  mainSections = []  # This removes the posts listing
  body_classes = "sans-serif bg-white"
  post_content_classes = "sans-serif"
  
[markup.goldmark.renderer]
  unsafe = true  # Allows raw HTML in markdown files

[menu]
  # Removing default menu items by not defining them
>>>>>>> ee9418652b7328595503d8123bd4b261f82fb8cd
