baseURL = "https://arranwalshe.com"
languageCode = "en-us"
title = "Arran Walshe"
theme = "ananke"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
  description = "Academic & Researcher"
  custom_css = ["/custom.css"]
  mainSections = []  # This removes the posts listing
  body_classes = "sans-serif bg-white"
  post_content_classes = "sans-serif"
  
[markup.goldmark.renderer]
  unsafe = true  # Allows raw HTML in markdown files

[menu]
  # Removing default menu items by not defining them
